<?php
/**
 * Model that provides tracking information for a claim batch that was processed using
 * the billing manager. Each file generated by the billing manager has an entry in the
 * billing_tracker_file table. The background process uses this table to find x12 files
 * that have to be sent via SFTP (using the credentials stored in Practice > X12 Partners)
 * to a remote server.
 *
 * @package   OpenEMR
 * @link      http://www.open-emr.org
 * @author    Ken Chapple <ken@mi-squared.com>
 * @copyright Copyright (c) 2021 Ken Chapple <ken@mi-squared.com>
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

namespace OpenEMR\Billing\BillingTracker;


class BillingTrackerFile
{

}
